use_frameworks!

platform :ios, '13.0'

target 'BRCFlexTagBox_Example' do
  pod 'BRCFlexTagBox', :path => '../../../BRCFlexTagBox'

  target 'BRCFlexTagBox_Tests' do
    inherit! :search_paths

    
  end
end
